server:
    port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/client/**
        - id: income-product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/incomes/**
        - id: outcome-product-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/outcomes/**
        - id: transaction-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/transaction/**
        - id: transfer-service
          uri: http://localhost:8085/
          predicates:
            - Path=/api/transfer/**