server:
    port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://banksystem-user001:mabU9mcbaKgUSFjf@cluster0.khamd.mongodb.net/OutcomeProductService
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

feing:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
